server:
  port: 8888
spring:
  jackson:
    date-format: yyyy-mm-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
      url: jdbc:mysql://139.224.111.105:3306/testdbmybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
    suffix: .html # 模版后缀名 默认为ftl
    charset: UTF-8 # 文件编码
    template-loader-path: classpath:/templates/
  quartz:
    job-store-type: jdbc  #数据库存储quartz任务配置
    jdbc:
      initialize-schema: never #自动初始化表结构，第一次启动的时候这里写always

mybatis:
#  配置mybatis的sql实现的位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    user_name -> userName  驼峰映射  默认就是true
    map-underscore-to-camel-case: true

# logback配置
#logging:
#  level:
#    com.unicom.zimugeyjb.dao: debug

#log4j2配置  有3个文件 对应3种环境
logging:
  config: classpath:log4j2-dev.xml
