server:
  port: 8888
spring:
  jackson:
    date-format: yyyy-mm-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
      url: jdbc:mysql://139.224.111.105:3306/testdbmybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
    suffix: .html # 模版后缀名 默认为ftl
    charset: UTF-8 # 文件编码
    template-loader-path: classpath:/templates/
  redis:
    database: 0 # Redis 数据库索引（默认为 0）
    host: 127.0.0.1 #Redis 服务器地址
    port: 6379  # Redis 服务器连接端口
    password: 123456 # Redis 服务器链接密码 （默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大链接数（使用负值 表示没有限制）默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 链接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中国的最小空闲连接 默认 0
  cache:
    type: redis
#    redis:
#      time-to-live: 600  #统一写过期时间10min  这样不好

caching:
  ttlmap:
    article: 10 #  article存储10秒
    articleAll: 20  #  articleAll存储20秒









mybatis:
#  配置mybatis的sql实现的位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    user_name -> userName  驼峰映射  默认就是true
    map-underscore-to-camel-case: true

# logback配置
#logging:
#  level:
#    com.unicom.zimugeyjb.dao: debug

#log4j2配置  有3个文件 对应3种环境
logging:
  config: classpath:log4j2-dev.xml
