server:
  port: 8888
spring:
  jackson:
    date-format: yyyy-mm-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/testdbJPA?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    primary:
#      jdbc-url: jdbc:mysql://127.0.0.1:3306/testdbJPA?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: root
#      driver-class-name: com.mysql.jdbc.Driver
#    secondary:
#      jdbc-url: jdbc:mysql://127.0.0.1:3306/testdbJPA2?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: root
#      driver-class-name: com.mysql.jdbc.Driver

    primary:
      url: jdbc:mysql://127.0.0.1:3306/testdbJPA?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      url: jdbc:mysql://127.0.0.1:3306/testdbJPA2?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  jta:
    atomikos:
      datasource:
        max-pool-size: 20
        borrow-connection-timeout: 60
      connectionfactory:
        max-pool-size: 20
        borrow-connection-timeout: 60