server:
  port: 8888
spring:
  jackson:
    date-format: yyyy-mm-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


#  CREATE TABLE `article` (
#  `id` int(11) NOT NULL auto_increment,
#  `author` varchar(32) DEFAULT NULL,
#  `title` varchar(32) DEFAULT NULL,
#  `content` varchar(512) DEFAULT NULL,
#  `cteateTime` datetime not null,
#  PRIMARY KEY (`id`)
#  );
