server:
  port: 8888
  servlet:
    context-path: /yangjiabin
spring:
  jackson:
    date-format: yyyy-mm-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
      url: jdbc:mysql://139.224.111.105:3306/testdbmybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
     cache: false # 启用缓存：建议生产开启
     check-template-location: true # 检查模板是否存在
     enable: true #s是否启用
     encoding: UTF-8
     excluded-view-names: #应该从解析中排出师徒名称列表(用逗号分隔)
     mode: HTML5 # 模板模式
     prefix: classpath:/templates/ # 模板存放路径
     suffix: .html #模板后缀



mybatis:
#  配置mybatis的sql实现的位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    user_name -> userName  驼峰映射  默认就是true
    map-underscore-to-camel-case: true

logging:
  level:
    com.unicom.zimugeyjb.dao: debug