server:
  port: 8888
  undertow:
    # 设置IO线程数，它主要执行非阻塞的任务，他们会负责多个连接，默认设置每个cpu核心一个线程
    io-threads: 4
    # 工作任务线程池，默认为io-threads的8倍
    worker-threads: 32



spring:
  jackson:
    date-format: yyyy-mm-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
      url: jdbc:mysql://139.224.111.105:3306/testdbmybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    cache: false # 缓存配置  开发阶段应该配置为false 因为经常会改
    # suffix: .html #模板默认为ftl
    suffix: .ftl #模板默认为ftl
    charset: UTF-8 # 文件编码
    template-loader-path: classpath:/templates/


context:
  listener:
    classes: com.unicom.zimugeyjb.customlistener.otherMethod.MyListener3

mybatis:
#  配置mybatis的sql实现的位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    user_name -> userName  驼峰映射  默认就是true
    map-underscore-to-camel-case: true

logging:
  level:
    com.unicom.zimugeyjb.dao: debug