server:
  port: 8888
spring:
  jackson:
    date-format: yyyy-mm-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
      url: jdbc:mysql://139.224.111.105:3306/testdbmybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/


mybatis:
#  配置mybatis的sql实现的位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    user_name -> userName  驼峰映射  默认就是true
    map-underscore-to-camel-case: true

logging:
  level:
    com.unicom.zimugeyjb.dao: debug